const String LoginViewRoute = "LoginView";
const String SignUpViewRoute = "SignUp";
const String HomeViewRoute = "HomeView";
const String ProfileViewRoute = "ProfileView";
const String FriendsViewRoute = "FriendsView";
const String WatchListViewRoute = "WatchListView";
const String MovieDetailsViewRoute = "MovieDetailsView";
const String TvShowDetailsViewRoute = "TvShowDetailsView";
const String PersonProfileViewRoute = "PersonProfileView";
const String StartupViewRoute = "StartupView";
// Generate the views here
