// These are constants for the route names ;

const String LoginViewRoute = "LoginView";
const String SignUpViewRoute = "SignUp";
const String HomeViewRoute = "HomeView";
const String ProfileViewRoute = "ProfileView";
const String FriendsViewRoute = "FriendsView";
const String WatchListViewRoute = "WatchListView";
const String MovieDetailsViewRoute = "MovieDetailsView";
const String TvShowDetailsViewRoute = "TvShowDetailsView";
const String PersonProfileViewRoute = "PersonProfileView";
const String StartupViewRoute = "StartupView";
const String ThemesViewRoute = "ThemesView";
const String VideoPlayerViewRoute = "VideoPlayerView";
const String ReviewsScreenRoute = "ReviewsView";
const String ResetPasswordViewRoute = "ResetView";
const String NewPostViewRoute = "NewPostView";
const String NewPostItemSearchViewRoute = "NewPostItemSearch";
const String MovieVerticalViewRoute = "MovieVerticalView";
const String TvShowVerticalViewRoute = "TvShowVerticalView";
const String AboutAppViewRoute = "AboutAppView";
const String MessagesViewRoute = "MessagesView";
const String ChatViewRoute = "ChatView";
